const INITIAL_PROVIDER = "initialProvider"
const SECOND_PROVIDER = "secondProvider"
const INITIAL_PROVIDER_SELECTED_CATEGORIES = "initialProviderSelectedCategories"
const SECOND_PROVIDER_SELECTED_CATEGORIES = "secondProviderSelectedCategories"
const GET_PROVIDERS = "getProviders"
const UPDATE_INITIAL_PROVIDER = "updateInitialProvider"
const UPDATE_INITIAL_PROVIDER_SELECTED_CATEGORIES = "updateInitialProviderSelectedCategories"
const UPDATE_SECOND_PROVIDER = "updateSecondProvider"
const UPDATE_SECOND_PROVIDER_SELECTED_CATEGORIES = "updateSecondProviderSelectedCategories"
const IS_SYNC_UP_COMPLETED = "isSyncUpCompleted"
const UPDATE_IS_SYNC_UP_COMPLETED = "updateIsSyncUpCompleted"
const SYNC_PROVIDERS_CONTACTS = "syncProvidersContacts"
const IS_FORM_LOADED = "isFormLoaded"

export {
  INITIAL_PROVIDER,
  SECOND_PROVIDER,
  UPDATE_INITIAL_PROVIDER,
  UPDATE_SECOND_PROVIDER,
  GET_PROVIDERS,
  INITIAL_PROVIDER_SELECTED_CATEGORIES,
  SECOND_PROVIDER_SELECTED_CATEGORIES,
  UPDATE_INITIAL_PROVIDER_SELECTED_CATEGORIES,
  UPDATE_SECOND_PROVIDER_SELECTED_CATEGORIES,
  IS_SYNC_UP_COMPLETED,
  UPDATE_IS_SYNC_UP_COMPLETED,
  SYNC_PROVIDERS_CONTACTS,
  IS_FORM_LOADED,
}